---
- name: 7k facts
  hosts: switches_nxapi
  connection: local
  tasks:
    - name: Get Nexus7k facts
      nxos_facts:
        #host: "{{inventory_hostname}}"
        #transport: nxapi
        use_ssl: yes
        validate_certs: no
      register: nxos_data

    - name: Print name to console
      debug: msg="{{nxos_data}}"
